/*
 * CSC 18B 42029 - Java Programming
 * Individual Project: Binary Game
 *
 * File name: MainFrame.java
 * Coded by : Jiwon Yoo
 */

package BinaryGame.Main;

import BinaryGame.Serializable.*;
import java.io.*;

/**
 * Splash / Main Screen;
 * User may click or press any key to continue;
 * Initializes file data for serialization;
 * 
 * @author astraea
 *
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainFrame() {
        initComponents();

        // play bgm
        Option.playBGM("src/sound/Solitud.wav");
        
        // vars used for serialization
        OptionSerializable record = new OptionSerializable();
        UsernameSerializable record2 = new UsernameSerializable();
        CreateDataFile data = new CreateDataFile();
        
        // if option_data file DNE, create initial option_data file
        File optionData = new File("option_data.txt");
            
        if(!optionData.exists()) {
            data.openFile(record);
            data.addRecords(record);
            data.closeFile();
        }
        
        // if username_data file DNE, create initial username_data file
        File usernameData = new File("username_data.txt");
        if(!usernameData.exists()) {
            data.openFile(record2);
            data.addRecords(record2);
            data.closeFile();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        matrixGIF = new javax.swing.JLabel();
        credit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Binary Game");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setName(""); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(1, 1, 1));
        panel.setPreferredSize(new java.awt.Dimension(800, 700));
        panel.setLayout(null);

        title.setFont(new java.awt.Font("Ubuntu", 0, 74)); // NOI18N
        title.setForeground(new java.awt.Color(253, 251, 251));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/splash/title.gif"))); // NOI18N
        panel.add(title);
        title.setBounds(80, 30, 661, 117);

        matrixGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/splash/greenmatrix.gif"))); // NOI18N
        panel.add(matrixGIF);
        matrixGIF.setBounds(150, 150, 520, 512);

        credit.setForeground(new java.awt.Color(51, 51, 51));
        credit.setText("Jiwon Yoo");
        panel.add(credit);
        credit.setBounds(10, 680, 90, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* press any key to continue */
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        this.setVisible(false);
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
    }//GEN-LAST:event_formKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.setVisible(false);
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame screen = new MainFrame();
                screen.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel credit;
    private javax.swing.JLabel matrixGIF;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
