/*
 * CSC 18B 42029 - Java Programming
 * Individual Project: Binary Game
 *
 * File name: OptionFrame.java
 * Coded by : Jiwon Yoo
 */

package BinaryGame.Main;

import BinaryGame.Serializable.ReadDataFile;
import BinaryGame.Serializable.*;
import javax.swing.*;

/**
 *     
 * @author astraea
 */
public class OptionFrame extends javax.swing.JFrame {
    private static OptionSerializable record = new OptionSerializable();
    // use serialization to save these vars
    private static int volume = 90;

    /**
     * Creates new form OptionFrame
     */
    public OptionFrame() {
        initComponents();
        
        // read data from a file
        ReadDataFile app = new ReadDataFile();
        app.openFile(record);
        record = app.readRecords(record);
        app.closeFile();
        
        switch(record.getVolume()) {
            case 90:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/nine.png"))); break;
            case 80:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/eight.png"))); break;
            case 70:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/seven.png"))); break;
            case 60:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/six.png"))); break;
            case 50:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/five.png"))); break;
            case 40:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/four.png"))); break;
            case 30:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/three.png"))); break;
            case 20:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/two.png"))); break;
            case 10:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/one.png"))); break;
            case 0:
                vState.setIcon(new ImageIcon(getClass().getResource("/image/option/zero.png"))); break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        vState = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        credit = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        volumeLabel = new javax.swing.JLabel();
        optionForm = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Binary Game: Option");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setName(""); // NOI18N
        setUndecorated(true);

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setMinimumSize(new java.awt.Dimension(800, 700));
        panel.setLayout(null);

        jSeparator1.setBackground(new java.awt.Color(71, 71, 71));
        jSeparator1.setForeground(new java.awt.Color(164, 1, 1));
        panel.add(jSeparator1);
        jSeparator1.setBounds(120, 460, 530, 20);

        jSeparator2.setBackground(new java.awt.Color(71, 71, 71));
        jSeparator2.setForeground(new java.awt.Color(164, 1, 1));
        panel.add(jSeparator2);
        jSeparator2.setBounds(120, 270, 530, 20);

        vState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/option/nine.png"))); // NOI18N
        vState.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vState.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                vStateMouseWheelMoved(evt);
            }
        });
        panel.add(vState);
        vState.setBounds(136, 120, 520, 134);

        jLabel1.setForeground(new java.awt.Color(159, 6, 6));
        jLabel1.setText("*use mouse wheel to change the volume");
        panel.add(jLabel1);
        jLabel1.setBounds(400, 240, 290, 30);

        credit.setForeground(new java.awt.Color(51, 51, 51));
        credit.setText("Jiwon Yoo");
        panel.add(credit);
        credit.setBounds(10, 680, 90, 20);

        title.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Option");
        panel.add(title);
        title.setBounds(290, 90, 210, 24);

        applyButton.setBackground(new java.awt.Color(21, 21, 21));
        applyButton.setFont(new java.awt.Font("Ubuntu Medium", 0, 14)); // NOI18N
        applyButton.setForeground(java.awt.Color.white);
        applyButton.setText("Apply");
        applyButton.setBorder(null);
        applyButton.setFocusPainted(false);
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        panel.add(applyButton);
        applyButton.setBounds(170, 500, 160, 40);

        backButton.setBackground(new java.awt.Color(21, 21, 21));
        backButton.setFont(new java.awt.Font("Ubuntu Medium", 0, 14)); // NOI18N
        backButton.setForeground(java.awt.Color.white);
        backButton.setText("Back");
        backButton.setBorder(null);
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        panel.add(backButton);
        backButton.setBounds(450, 500, 160, 40);

        volumeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/option/volume.png"))); // NOI18N
        panel.add(volumeLabel);
        volumeLabel.setBounds(130, 160, 220, 50);

        optionForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/option/optionForm.png"))); // NOI18N
        panel.add(optionForm);
        optionForm.setBounds(100, 70, 590, 510);

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/matrix.gif"))); // NOI18N
        panel.add(bg1);
        bg1.setBounds(410, -10, 400, 440);

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/matrix.gif"))); // NOI18N
        panel.add(bg2);
        bg2.setBounds(0, -10, 400, 440);

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/matrix.gif"))); // NOI18N
        panel.add(bg3);
        bg3.setBounds(0, 290, 400, 440);

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/matrix.gif"))); // NOI18N
        panel.add(bg4);
        bg4.setBounds(410, 290, 400, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
     * change the volume of BGM
     * using mouse wheel
     */
    private void vStateMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_vStateMouseWheelMoved
        // when changing the volume between 1-8 (not min and max),
        // play the sound effect
        if(!(vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-8) + "zero.png") ||
                vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-8) + "nine.png"))) {
             Option.soundEffect("src/sound/robot blip.wav");
        }
        
        // inc or dec the volume based on mouse wheel
        switch(evt.getWheelRotation()) {
            // if mouse wheel moved positive way,
            // increased the volume.
            case 1: {
                if(evt.getWheelRotation() == 1 &&
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-8) + "zero.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/one.png")));
                    volume = 10;
                } else if(evt.getWheelRotation() == 1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-7) + "one.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/two.png")));
                    volume = 20;
                } else if(evt.getWheelRotation() == 1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-7) + "two.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/three.png")));
                    volume = 30;
                } else if(evt.getWheelRotation() == 1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-9) + "three.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/four.png")));
                    volume = 40;
                } else if(evt.getWheelRotation() == 1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-8) + "four.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/five.png")));
                    volume = 50;
                } else if(evt.getWheelRotation() == 1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-8) + "five.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/six.png")));
                    volume = 60;
                } else if(evt.getWheelRotation() == 1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-7) + "six.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/seven.png")));
                    volume = 70;
                } else if(evt.getWheelRotation() == 1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-9) + "seven.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/eight.png")));
                    volume = 80;
                } else if(evt.getWheelRotation() == 1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-9) + "eight.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/nine.png")));
                    volume = 90;
                }
            }break;
            // if mouse wheel moved negative way,
            // decrease the volume.
            case -1: {
                if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-7) + "one.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/zero.png")));
                    volume = 0;
                } else if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-7) + "two.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/one.png")));
                    volume = 10;
                } else if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-9) + "three.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/two.png")));
                    volume = 20;
                } else if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-8) + "four.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/three.png")));
                    volume = 30;
                } else if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-8) + "five.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/four.png")));
                    volume = 40;
                } else if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-7) + "six.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/five.png")));
                    volume = 50;
                } else if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-9) + "seven.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/six.png")));
                    volume = 60;
                } else if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-9) + "eight.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/seven.png")));
                    volume = 70;
                } else if(evt.getWheelRotation() == -1 && 
                        vState.getIcon().toString().equals(vState.getIcon().toString().substring(0, vState.getIcon().toString().length()-8) + "nine.png")) {
                    vState.setIcon(new ImageIcon(getClass().getResource("/image/option/eight.png")));
                    volume = 80;
                }
            } break;
        }
    }//GEN-LAST:event_vStateMouseWheelMoved

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Option.soundEffect("src/sound/Short Circuit.wav");
        LoginFrame login = new LoginFrame();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /*
     * save all the changes when
     * apply is clicked.
     */
    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        Option.soundEffect("src/sound/Short Circuit.wav");
        
        Option.applyChanges(volume);
        
        LoginFrame login = new LoginFrame();
        this.setVisible(false);
        login.setVisible(true);
        
    }//GEN-LAST:event_applyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel credit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel optionForm;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel vState;
    private javax.swing.JLabel volumeLabel;
    // End of variables declaration//GEN-END:variables
}
