/*
 * CSC 18B 42029 - Java Programming
 * Individual Project: Binary Game
 *
 * File name: PlayMenuFrame.java
 * Coded by : Jiwon Yoo
 */

package BinaryGame.Main;

/**
 *
 * @author rcc
 */
public class PlayMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public PlayMenuFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        quitLabel = new javax.swing.JLabel();
        playLabel = new javax.swing.JLabel();
        multiLabel = new javax.swing.JLabel();
        matrixGIF = new javax.swing.JLabel();
        credit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Binary Game");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setName(""); // NOI18N
        setUndecorated(true);
        setResizable(false);

        panel.setBackground(new java.awt.Color(1, 1, 1));
        panel.setMinimumSize(new java.awt.Dimension(800, 700));
        panel.setPreferredSize(new java.awt.Dimension(800, 700));
        panel.setLayout(null);

        quitLabel.setFont(new java.awt.Font("Gadugi", 0, 48)); // NOI18N
        quitLabel.setForeground(new java.awt.Color(51, 153, 0));
        quitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/quit.png"))); // NOI18N
        quitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quitLabelMouseExited(evt);
            }
        });
        panel.add(quitLabel);
        quitLabel.setBounds(260, 586, 312, 64);

        playLabel.setFont(new java.awt.Font("Gadugi", 0, 48)); // NOI18N
        playLabel.setForeground(new java.awt.Color(51, 153, 0));
        playLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/play.png"))); // NOI18N
        playLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playLabelMouseExited(evt);
            }
        });
        panel.add(playLabel);
        playLabel.setBounds(260, 422, 312, 64);

        multiLabel.setFont(new java.awt.Font("Gadugi", 0, 48)); // NOI18N
        multiLabel.setForeground(new java.awt.Color(51, 153, 0));
        multiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/multi.png"))); // NOI18N
        multiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiLabelMouseEntered(evt);
            }
        });
        panel.add(multiLabel);
        multiLabel.setBounds(180, 500, 480, 64);

        matrixGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/splash/greenmatrix.gif"))); // NOI18N
        panel.add(matrixGIF);
        matrixGIF.setBounds(150, 0, 490, 490);

        credit.setForeground(new java.awt.Color(51, 51, 51));
        credit.setText("Jiwon Yoo");
        panel.add(credit);
        credit.setBounds(10, 680, 90, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
     * change the label effect when mouse is hovered.
     * And change it back to the original when
     * mouse exits the label
     */
    private void playLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playLabelMouseEntered
        playLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/playHover.gif")));
        Option.soundEffect("src/sound/robot blip.wav");
    }//GEN-LAST:event_playLabelMouseEntered

    private void playLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playLabelMouseExited
        playLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/play.png")));
    }//GEN-LAST:event_playLabelMouseExited

    private void multiLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiLabelMouseEntered
        multiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/multiHover.gif")));
        Option.soundEffect("src/sound/robot blip.wav");
    }//GEN-LAST:event_multiLabelMouseEntered

    private void multiLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiLabelMouseExited
        multiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/multi.png")));
    }//GEN-LAST:event_multiLabelMouseExited

    private void quitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseEntered
       quitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/quitHover.gif")));
       matrixGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/splash/redmatrix.gif")));
       Option.soundEffect("src/sound/robot blip.wav");
    }//GEN-LAST:event_quitLabelMouseEntered

    private void quitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseExited
        quitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main menu/quit.png")));
        matrixGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/splash/greenmatrix.gif")));
    }//GEN-LAST:event_quitLabelMouseExited

    private void quitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseClicked
        LoginFrame login = new LoginFrame();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_quitLabelMouseClicked

    private void playLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playLabelMouseClicked
        Option.soundEffect("src/sound/Right Channel Scramble.wav");
        GameModeFrame screen = new GameModeFrame();
        this.setVisible(false);
        screen.setVisible(true);
    }//GEN-LAST:event_playLabelMouseClicked

    private void multiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiLabelMouseClicked
        Option.soundEffect("src/sound/Right Channel Scramble.wav");
    }//GEN-LAST:event_multiLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel credit;
    private javax.swing.JLabel matrixGIF;
    private javax.swing.JLabel multiLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel playLabel;
    private javax.swing.JLabel quitLabel;
    // End of variables declaration//GEN-END:variables
}
